version: "3.7"

services:
  database:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: P123456p
      MYSQL_DATABASE: phonebook
      MYSQL_USER: admin
      MYSQL_PASSWORD: Bekir1234
    networks:
      - phonenet

  myapp:
    image: blgsyrc0560/phonebook:1.0
    container_name: phonebookapp
    restart: always
    depends_on:
      - database
    ports:
      - 80:80
    networks:
      - phonenet

networks:
  phonenet:
    driver: bridge
